name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
# A job that checks all md files and creates images from the frontmatter configuration
#
#  generate_og_job:
#    runs-on: ubuntu-latest
#    name: Generate OG Images
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v1
#      - name: Generate Image
#        uses: BoyWithSilverWings/generate-og-image@1.0.3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        with:
#          path: src/static/og-images/
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run generate

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: uselinked.com
